-- Admin Dashboard Setup
-- This script adds the necessary tables, policies, and functions for role-based access control.

BEGIN;

-- 1. Create admin_roles table
CREATE TABLE IF NOT EXISTS public.admin_roles (
    user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('admin', 'super_admin')),
    created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.profiles (id, full_name, email)
SELECT
    id,
    COALESCE(
        NULLIF(raw_user_meta_data->>'full_name', ''),
        NULLIF(raw_user_meta_data->>'name', ''),
        split_part(email, '@', 1)
    ) AS full_name,
    email
FROM auth.users
ON CONFLICT (id) DO UPDATE
SET full_name = excluded.full_name,
    email = excluded.email,
    updated_at = now();

-- admin_roles is only read from the server with the service role key.
-- Disable RLS here to avoid recursive policy evaluation.
ALTER TABLE public.admin_roles DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins can read admin_roles" ON public.admin_roles;

DROP POLICY IF EXISTS "Admins can read all profiles" ON public.profiles;
CREATE POLICY "Admins can read all profiles" ON public.profiles
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.admin_roles WHERE user_id = auth.uid())
  );

-- 2. Audit Logs Table (Optional but recommended for dashboard actions)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    action text NOT NULL,
    table_name text NOT NULL,
    record_id text,
    created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can read audit_logs" ON public.audit_logs
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.admin_roles WHERE user_id = auth.uid())
  );

-- 3. Update RLS policies on Places to restrict write operations to admins only

-- Remove the public write policy if it exists (from the MVP setup)
DROP POLICY IF EXISTS "Public write places" ON public.places;

-- Re-add places write policies only for admins
CREATE POLICY "Admins can insert places" ON public.places
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.admin_roles WHERE user_id = auth.uid())
  );

CREATE POLICY "Admins can update places" ON public.places
  FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.admin_roles WHERE user_id = auth.uid())
  );

CREATE POLICY "Admins can delete places" ON public.places
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM public.admin_roles WHERE user_id = auth.uid())
  );

-- 4. Admin policies for Reviews (Admins can delete any review)
CREATE POLICY "Admins can delete any review" ON public.reviews
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM public.admin_roles WHERE user_id = auth.uid())
  );

COMMIT;

-- INSTRUCTIONS:
-- 1. Run this script in your Supabase SQL Editor.
-- 2. To grant yourself admin access, insert your user_id into admin_roles:
--    INSERT INTO public.admin_roles (user_id, role) VALUES ('your-uuid-here', 'super_admin');
